os: osx
language: swift
osx_image: xcode9

branches:
    only:
    - master

script:
    - xcodebuild clean build test -project SwiftIcons.xcodeproj -scheme SwiftIcons -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0' CODE_SIGNING_REQUIRED=NO | xcpretty
    - pod lib lint

notifications:
email:
    on_success: never
    on_failure: change
